config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  # root "cars#index"
  resources :cars, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :favourites, only: [:create]
  end

  resources :favourites, only: [:index, :destroy]
end

# get "up" => "rails/health#show", as: :rails_health_check

# resources :cars, only: [:index, :show] do
#   resources :reviews, only: [:create]
#   resources :favourites, only: [:create]
# end
# resources :favourites, only: [:index, :destroy]

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :owner

  has_many :favourites
  has_many :reviews

  validates :brand, :model, :year, :fuel, presence: true
  validates :year, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 2025 }
end

app/models/favourite.rb
class Favourite < ApplicationRecord
  belongs_to :car
end

app/models/owner.rb
class Owner < ApplicationRecord

  validates :nickname, presence: true
  has_many :cars, dependent: :destroy

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :car
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
  has_many :cars, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController


  def index
    @cars = Car.all
  end

  def show
    @car = Car.find(params[:id])
    @review = Review.new
    @favourite = Favourite.new
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController

  def index
    @favourites = Favourite.all
  end

  def create
    @car = Car.find(params[:car_id])
    @favourite = Favourite.new
    @favourite.car = @car

    if @favourite.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  def destroy
    @favourite = Favourite.find(params['id'])
    @favourite.destroy
    redirect_to favourites_path, status: :see_other
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
  end

  def create
    # @review = Review.new(review_params)
    @car = Car.find(params[:car_id])
    @review = Review.new(review_params)
    @review.car = @car
    if @review.save
      redirect_to car_path(@car)
    else
      render 'cars/show', status: :unprocessable_entity
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cars/index.html.erb
<h1>Cars</h1>
<ul>
<% @cars.each do |car|%>
  <%= link_to car_path(car) do %>
  <li>
    <%= car.brand %>
  </li>
  <% end %>
<% end %>
</ul>
<p><%= link_to "Your Garage", favourites_path %></p>

app/views/cars/show.html.erb
<h1><%= @car.brand %></h1>
<h2> <%= @car.model %> </h2>
<h3> <%= @car.fuel %></h3>
<p> <%= @car.year  %></p>

<% if @car.favourites.empty? %>
  <%= simple_form_for [@car, @favourite] do |f| %>
    <%= f.submit "Add to your garage", class: "btn btn-primary" %>
  <% end %>
<% else %>
  <p>This car is already in your garage</p>
<% end %>

<hr>

<h1> Create a review</h1>
<%= simple_form_for [@car, @review] do |f| %>
<%= f.input :comment, placeholder: "Comment here" %>
<%= f.input :rating, collection: 1..5 %>
<%= f.submit "submit review", class: "btn btn-primary" %>
<% end %>

<h2>Reviews</h2>
<% @car.reviews.each do |review|  %>
  <p><%= review.comment %></p>
  <p>Rating: <%= review.rating  %></p>
  <p>=====================</p>
<% end %>
<p><%= link_to "Home", cars_path %></p>
<p><%= link_to "Your Garage", favourites_path %></p>

app/views/favourites/index.html.erb
<h1>My Garage</h1>
<ul>
  <% @favourites.each do |favourite| %>
  <%= link_to car_path(favourite.car) do %>
  <p><%= favourite.car.brand %>
  <% end  %>
  <%= link_to "Delete from Garage",
  favourite_path(favourite),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure"}
  %>
  </p>
  <% end %>
</ul>
<%=  link_to "Home", cars_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsAwesomeGarage</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<h1> Create a review</h1>
<%= simple_form_for @review do |f| %>
<%= f.input  %>